### ISSUE TITLE
Using tileserver-gl in docker-compose linked containers

### ISSUE THREAD

**Issue by psychemedia** [klokantech/tileserver-gl#181]
Are there any examples of using `tileserver-gl` with linked containers launched using `docker-compose`?

For example

Related to this, is it possible to define the Dockerfile such that it would allow the setting of environment variables in the `docker-compose.yaml` file that would allow the setting of the `-b`,` --bind` (*bind address*) ?

````
tileserver:
  image: klokantech/tileserver-gl
  ports:
    - 8085:80
  volumes:
    - .:/data
 
jupyterscipy:
  image: psychemedia/ou-tm351-jupyter-custom-pystack-test
  ports:
    - 8899:8888
  links:
    - tileserver:tileserver
    - postcodes:postcodes 
  volumes:
    - .:/home/jovyan/work
````

but can seem to load any served tiles in a map in a Jupyter notebook in the linked Jupyter container?

I'm wondering if it's a bind issue?
