### ISSUE TITLE
How can I use "--verbose" in Dockerfile?

### ISSUE THREAD

**Issue by gmuc** [klokantech/tileserver-gl#238]
I use 

`docker run --rm -it -v $(pwd):/data -p 8080:80 klokantech/tileserver-gl --verbose`

now I want use it in Dockerfile

```
FROM klokantech/tileserver-gl:v2.2.0
ARG "--verbose"
ADD . /data
```
and docker-compose.yaml

```
version: '2.1'
services:
  tileserver:
    build: tileserver
    ports:
    - "8080:80"
```

The server run but "--verbose" not work, if I start docker-compose. Why?
